// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1w59EqtroPgVu9I82CuoZO8qesGNhlxY',
    appId: '1:1015803770585:web:43bb3d0c3ac7a1b47870c8',
    messagingSenderId: '1015803770585',
    projectId: 'meliorabags',
    authDomain: 'meliorabags.firebaseapp.com',
    storageBucket: 'meliorabags.appspot.com',
    measurementId: 'G-1WLD9EXRFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuL31emEIRYSi34PhwQXsN8voaWXyJkjw',
    appId: '1:1015803770585:android:ec615e63e4d5422e7870c8',
    messagingSenderId: '1015803770585',
    projectId: 'meliorabags',
    storageBucket: 'meliorabags.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASTcYY9WJjZ03z4ebel43fb6gnNW0z5EI',
    appId: '1:1015803770585:ios:b20dbd4449a7326c7870c8',
    messagingSenderId: '1015803770585',
    projectId: 'meliorabags',
    storageBucket: 'meliorabags.appspot.com',
    iosClientId: '1015803770585-ih7iopcblli0cs60kcldditpok44arhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.meliorabag',
  );
}
